@startuml seq_tich_diem_nang_hang
skinparam defaultFontName Arial
skinparam sequenceArrowThickness 2
skinparam roundcorner 8
skinparam sequenceParticipantBorderColor #3B82F6
skinparam sequenceParticipantBackgroundColor #DBEAFE

title Tich Diem & Tu Dong Nang Hang

participant "InvoiceService /\nPaymentFlow" as INV
participant "PointService\n(Impl)" as PS
participant "CustomerRepository" as CR
participant "PointHistoryRepository" as PHR
database "Database" as DB


INV -> PS: addPoints(customer, invoice, earnedPoints)

PS -> CR: findById(customerId)
CR -> DB: SELECT * FROM Customer WHERE id=?
DB --> CR: Customer data
CR --> PS: customer object

PS -> PS: Tinh diem = floor(totalAmount x 5%)
PS -> PS: customer.rewardPoints += earnedPoints
PS -> PS: customer.totalSpent += totalAmount

PS -> PS: Kiem tra nguong TotalSpent

alt TotalSpent >= 5,000,000 va Tier < GOLD
  PS -> PS: customer.tier = GOLD
  PS -> CR: update(customer)
  CR -> DB: UPDATE Customer SET tier='GOLD', rewardPoints=?, totalSpent=?
  DB --> CR: OK
else TotalSpent >= 2,000,000 va Tier < SILVER
  PS -> PS: customer.tier = SILVER
  PS -> CR: update(customer)
  CR -> DB: UPDATE Customer SET tier='SILVER', rewardPoints=?, totalSpent=?
  DB --> CR: OK
else Khong can nang hang
  PS -> CR: update(customer)
  CR -> DB: UPDATE Customer SET rewardPoints=?, totalSpent=?
  DB --> CR: OK
end

PS -> PHR: save(PointHistory{type=EARN, points, invoiceId, customerId})
PHR -> DB: INSERT INTO PointHistory (...)
DB --> PHR: OK
PHR --> PS: saved

PS --> INV: done
@enduml
